In [1]:
import cv2
import os
import numpy as np

# Loading and Displaying Image

In [2]:
Img=cv2.imread('cv.jpg')


In [3]:
cv2.imshow('tab',Img)
cv2.waitKey()
cv2.destroyAllWindows()

# Saving Image

In [4]:
cv2.imwrite('output/out_img.png',Img)

True

In [5]:
new_img=cv2.imread('output/out_img.png')

In [6]:
cv2.imshow('new image',new_img)
cv2.waitKey()
cv2.destroyAllWindows()

# Accessing pixels in Image

In [7]:
Img.shape

(720, 1280, 3)

In [8]:
Img[:200,:500,:]=0

In [9]:
cv2.imshow('new',Img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img_crop=new_img[400:,200:500]

In [11]:
cv2.imshow('cropped',img_crop)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
new_img[:,:,0]=255
new_img[:,:,1]=255
new_img[:,:,2]=0

In [13]:
cv2.imshow('cropped',new_img)
cv2.waitKey()
cv2.destroyAllWindows()

# Drawing on Images

In [14]:
canvas=np.ones((500,500,3),dtype='uint8')
canvas[:,:,:]=255

In [15]:
cv2.imshow('cropped',canvas)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
red=(255,0,0)
cv2.line(canvas,(0,0),(500,500),red,5)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [18]:
cv2.imshow('tab', canvas)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
green=(0,255,0)
cv2.rectangle(canvas,(0,0),(500,500),green,5)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [30]:
cv2.imshow('tab', canvas)
cv2.waitKey()
cv2.destroyAllWindows()

In [33]:
blue=(0,0,255)
cv2.ellipse(canvas,(250,250),(100,100),45,0,360,blue)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [34]:
cv2.imshow('tab', canvas)
cv2.waitKey()
cv2.destroyAllWindows()

# Image Transformation

In [2]:
img=cv2.imread('test.jpg')

In [3]:
cv2.imshow('tab', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
rows,col,ch=img.shape

In [8]:
pts1 = np.float32([[50, 50],
                   [200, 50], 
                   [50, 200]])
  
pts2 = np.float32([[10, 100],
                   [200, 50], 
                   [100, 250]])
  
M = cv2.getAffineTransform(pts1, pts2)

In [9]:
#M=np.float32([[50,0,10],[10,0,100]])

In [10]:
shifted=cv2.warpAffine(img,M,(col,rows))

In [12]:
cv2.imshow('tab', shifted)
cv2.waitKey()
cv2.destroyAllWindows()