In [42]:
import cv2
import os
import numpy as np
%config Completer.use_jedi = False

# Loading and Displaying Image

In [3]:
Img=cv2.imread('Data/cv.jpg')


In [4]:
cv2.imshow('tab',Img)
cv2.waitKey()
cv2.destroyAllWindows()

# Saving Image

In [5]:
cv2.imwrite('output/out_img.png',Img)

True

In [6]:
new_img=cv2.imread('output/out_img.png')

In [7]:
cv2.imshow('new image',new_img)
cv2.waitKey()
cv2.destroyAllWindows()

# Accessing pixels in Image

In [8]:
Img.shape

(720, 1280, 3)

In [9]:
Img[:200,:500,:]=0

In [10]:
cv2.imshow('new',Img)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
img_crop=new_img[400:,200:500]

In [12]:
cv2.imshow('cropped',img_crop)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
new_img[:,:,0]=255
new_img[:,:,1]=255
new_img[:,:,2]=0

In [14]:
cv2.imshow('cropped',new_img)
cv2.waitKey()
cv2.destroyAllWindows()

# Drawing on Images

In [15]:
canvas=np.ones((500,500,3),dtype='uint8')
canvas[:,:,:]=255

In [16]:
cv2.imshow('cropped',canvas)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
red=(255,0,0)
cv2.line(canvas,(0,0),(500,500),red,5)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [18]:
cv2.imshow('tab', canvas)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
green=(0,255,0)
cv2.rectangle(canvas,(0,0),(500,500),green,5)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [20]:
cv2.imshow('tab', canvas)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
blue=(0,0,255)
cv2.ellipse(canvas,(250,250),(100,100),45,0,360,blue)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [22]:
cv2.imshow('tab', canvas)
cv2.waitKey()
cv2.destroyAllWindows()

# Image Transformation

## Translation

In [23]:
img=cv2.imread('Data/test.jpg')

In [24]:
cv2.imshow('tab', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [25]:
rows,col,ch=img.shape

In [26]:
pts1 = np.float32([[50, 50],
                   [200, 50], 
                   [50, 200]])
  
pts2 = np.float32([[10, 100],
                   [200, 50], 
                   [100, 250]])
  
M = cv2.getAffineTransform(pts1, pts2)

In [27]:
#M=np.float32([[50,0,10],[10,0,100]])

In [28]:
shifted=cv2.warpAffine(img,M,(col,rows))

In [29]:
cv2.imshow('tab', shifted)
cv2.waitKey()
cv2.destroyAllWindows()

## Flip

In [78]:
img=cv2.imread('Data/cv.jpg')

In [79]:
cv2.imshow('tab',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
flip_img=cv2.flip(img,0)

In [33]:
cv2.imshow('tab',flip_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [34]:
flip_img1=cv2.flip(img,-1)

In [35]:
cv2.imshow('tab',flip_img1)
cv2.waitKey()
cv2.destroyAllWindows()

## Resize

In [36]:
scaled=cv2.resize(img,(400,400),fx=2,fy=2,interpolation=cv2.INTER_AREA)
cv2.imshow('tab', scaled)
cv2.waitKey()
cv2.destroyAllWindows()

In [37]:
scaled=cv2.resize(img,(400,400),fx=2,fy=2,interpolation=cv2.INTER_CUBIC)
cv2.imshow('tab', scaled)
cv2.waitKey()
cv2.destroyAllWindows()

## Cropping

In [39]:
cropped=img[0:300,0:500]
cv2.imshow('tab', cropped)
cv2.waitKey()
cv2.destroyAllWindows()

# Image Arithmatic

## addition

In [48]:
add=np.ones(img.shape,dtype='uint8')*100
print(add)

[[[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 ...

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]]


In [49]:
add_img=cv2.add(img,add)
cv2.imshow('tab',add_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [51]:
sub=np.ones(img.shape,dtype='uint8')*10
sub_img=cv2.subtract(img,sub)
cv2.imshow('tab',sub_img)
cv2.waitKey()
cv2.destroyAllWindows()

# Bitwise Operation

In [59]:
rect=np.ones((400,400),dtype='uint8')
cv2.rectangle(rect,(60,60),(320,320),255,-1)
cv2.imshow('tab',rect)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:
circle=np.ones((400,400),dtype='uint8')
cv2.circle(circle,(200,200),200,255,-1)
cv2.imshow('tab',circle)
cv2.waitKey()
cv2.destroyAllWindows()

In [61]:
bit_and=cv2.bitwise_and(rect,circle)
cv2.imshow('tab',bit_and)
cv2.waitKey()
cv2.destroyAllWindows()

In [62]:
bit_or=cv2.bitwise_or(rect,circle)
cv2.imshow('tab',bit_or)
cv2.waitKey()
cv2.destroyAllWindows()

In [63]:
bit_not=cv2.bitwise_not(rect)
cv2.imshow('tab',bit_not)
cv2.waitKey()
cv2.destroyAllWindows()

In [64]:
bit_xor=cv2.bitwise_xor(rect,circle)
cv2.imshow('tab',bit_xor)
cv2.waitKey()
cv2.destroyAllWindows()

# Masking

In [77]:
mask = np.zeros(img.shape[:2],dtype='uint8')
cv2.circle(mask,(img.shape[1]//2, img.shape[0]//2),100,255,-1)
cv2.circle(mask,(10,10),50,170,-1)
cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()
re_img=np.ones(img.shape,dtype='uint8')
cv2.rectangle(re_img,(30,30),(450,450),255,-1)
cv2.imshow('re', re_img)
cv2.waitKey()
cv2.destroyAllWindows()
rrre=cv2.bitwise_and(img, re)
cv2.imshow('rrre', rrre)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.bitwise_and(img, re,masked, mask = mask)
cv2.imshow('mask', masked)
cv2.waitKey()
cv2.destroyAllWindows()

# Color Channel Splitting and Color spaces

## Color channel splitting

In [83]:
color_img=cv2.imread('Data/cv.jpg')
b,g,r=cv2.split(color_img)
cv2.imshow('raw',color_img)
cv2.imshow('r',r)
cv2.imshow('g',g)
cv2.imshow('b',b)
cv2.waitKey()
cv2.destroyAllWindows()

In [84]:
merged=cv2.merge([b,g,r])
cv2.imshow('merged',merged)
cv2.waitKey()
cv2.destroyAllWindows()

In [86]:
zeros = np.zeros(color_img.shape[:2], dtype='uint8')
cv2.imshow('red', cv2.merge([zeros, zeros,r]))
cv2.imshow('green', cv2.merge([zeros,g,zeros]))
cv2.imshow('blue',cv2.merge([b,zeros,zeros]))
cv2.waitKey()
cv2.destroyAllWindows()

## color spaces

In [87]:
gray=cv2.cvtColor(color_img,cv2.COLOR_BGR2GRAY)
hsv=cv2.cvtColor(color_img,cv2.COLOR_BGR2HSV)
lab=cv2.cvtColor(color_img,cv2.COLOR_BGR2LAB)

In [88]:
cv2.imshow('bulb', color_img)
cv2.imshow('gray', gray)
cv2.imshow('hsv', hsv)
cv2.imshow('lab',lab)
cv2.waitKey()
cv2.destroyAllWindows()